### ISSUE TITLE
What is purpose of S340_and_TSDZ2_remote.hex ?

### ISSUE THREAD

**Issue by stsdc** [OpenSource-EBike-firmware/TSDZ2_wireless-bootloader#16]

**Comment by rananna** [comment]
Used for debugging only. Allows for easier bootloader testing with an application. In this case, the remote control. Unneeded now the bootloader is developed.

**Comment by stsdc** [comment]
So, can be deleted?

**Comment by rananna** [comment]
Fixed in the last PR
